"""empty message

Revision ID: 7c6202eba869
Revises: 
Create Date: 2020-02-18 16:17:44.761734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6202eba869'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_price', sa.Float(), nullable=True),
    sa.Column('product_name', sa.String(length=60), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
