"""empty message

Revision ID: 95c1ed4a80ad
Revises: 7c6202eba869
Create Date: 2020-02-20 17:24:54.654974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c1ed4a80ad'
down_revision = '7c6202eba869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_price', sa.Float(), nullable=True),
    sa.Column('product_name', sa.String(length=60), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
